function com_example_workshop_widgetset_Workshop_exampleWidgetset(){var Y='',V=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',cb='");',ub='#',Hb='.cache.js',wb='/',Cb='//',Fb='273CF4DA6BB756A75DF2D11D12C3ED46',Gb=':',lb='::',X='<!doctype html>',Z='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',qb='Bad handler "',W='CSS1Compat',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',Bb='base',zb='baseUrl',L='begin',R='body',K='bootstrap',yb='clear.cache.gif',O='com.example.workshop.widgetset.Workshop_exampleWidgetset',Eb='com.example.workshop.widgetset.Workshop_exampleWidgetset.devmode.js',Ab='com.example.workshop.widgetset.Workshop_exampleWidgetset.nocache.js',kb='com.example.workshop.widgetset.Workshop_exampleWidgetset::',nb='content',Jb='end',bb='eval("',M='gwt.codesvr.com.example.workshop.widgetset.Workshop_exampleWidgetset=',N='gwt.codesvr=',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',hb='head',S='iframe',xb='img',eb='javascript',T='javascript:""',Ib='loadExternalRefs',ib='meta',gb='moduleRequested',fb='moduleStartup',jb='name',U='position:absolute; width:0; height:0; border:none; left: -1000px;',db='script',Db='selectingPermutation',P='startup',$='undefined';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_example_workshop_widgetset_Workshop_exampleWidgetset.__sendStats=r;com_example_workshop_widgetset_Workshop_exampleWidgetset.__moduleName=O;com_example_workshop_widgetset_Workshop_exampleWidgetset.__errFn=null;com_example_workshop_widgetset_Workshop_exampleWidgetset.__moduleBase=Q;com_example_workshop_widgetset_Workshop_exampleWidgetset.__softPermutationId=0;com_example_workshop_widgetset_Workshop_exampleWidgetset.__computePropValue=null;com_example_workshop_widgetset_Workshop_exampleWidgetset.__getPropMap=null;com_example_workshop_widgetset_Workshop_exampleWidgetset.__gwtInstallCode=function(){};com_example_workshop_widgetset_Workshop_exampleWidgetset.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(R)[0]}
function B(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==W?X:Y;v.write(b+Z);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(db);g.language=eb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(db);g.language=eb;g.text=c[i];e.appendChild(g);d(e,g)}}}
com_example_workshop_widgetset_Workshop_exampleWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;p.getElementsByTagName(hb)[0].appendChild(n)}
com_example_workshop_widgetset_Workshop_exampleWidgetset.__startLoadingFragment=function(a){return G(a)};com_example_workshop_widgetset_Workshop_exampleWidgetset.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(db);c.language=eb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,Y);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Y}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_example_workshop_widgetset_Workshop_exampleWidgetset.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):Y}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=t(zb);if(a!=null){return a}return Y}
function h(){var a=p.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return Y}
function i(){var a=p.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return Y}
function j(){var a=p.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Y){k=h()}if(k==Y){k=i()}if(k==Y&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_example_workshop_widgetset_Workshop_exampleWidgetset.__moduleBase+a}
function H(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
s=function(a,b){return b in h[a]};com_example_workshop_widgetset_Workshop_exampleWidgetset.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_example_workshop_widgetset_Workshop_exampleWidgetset.__computePropValue=j;o.__gwt_activeModules[O].bindings=com_example_workshop_widgetset_Workshop_exampleWidgetset.__getPropMap;r(K,Db);if(q()){return G(Eb)}var k;try{k=Fb;var l=k.indexOf(Gb);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}com_example_workshop_widgetset_Workshop_exampleWidgetset.__softPermutationId=g;return G(k+Hb)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Ib,L);r(Ib,Jb)}
D();com_example_workshop_widgetset_Workshop_exampleWidgetset.__moduleBase=F();u[O].moduleBase=com_example_workshop_widgetset_Workshop_exampleWidgetset.__moduleBase;var J=H();I();r(K,Jb);C(J);return true}
com_example_workshop_widgetset_Workshop_exampleWidgetset.succeeded=com_example_workshop_widgetset_Workshop_exampleWidgetset();